-- CivicLens core data model. Apply this migration in the Supabase SQL editor
-- or through the Supabase CLI before deploying the updated application.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    full_name text not null default '',
    phone text not null default '',
    organization text not null default '',
    role text not null default '',
    subscription_plan text not null default 'basic'
        check (subscription_plan in ('basic', 'professional', 'enterprise')),
    notification_preferences jsonb not null default '{"mentionAlerts": false, "dailySummary": false, "emailNotifications": false}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.profiles
    add column if not exists notification_preferences jsonb not null
        default '{"mentionAlerts": false, "dailySummary": false, "emailNotifications": false}'::jsonb;

create table if not exists public.leaders (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    full_name text not null,
    public_name text not null default '',
    position text not null default '',
    organization text not null default '',
    keywords text not null default '',
    nicknames text not null default '',
    monitoring_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.mentions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    leader_id uuid references public.leaders(id) on delete set null,
    leader_name text not null,
    platform text not null,
    external_id text,
    author_name text,
    author_handle text,
    content text not null,
    post_url text,
    sentiment text not null default 'neutral'
        check (sentiment in ('positive', 'neutral', 'negative')),
    published_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.collection_runs (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    status text not null check (status in ('running', 'completed', 'completed_with_errors', 'failed')),
    result jsonb not null default '{}'::jsonb,
    started_at timestamptz not null default now(),
    finished_at timestamptz
);

create index if not exists leaders_user_created_at_idx
    on public.leaders (user_id, created_at desc);
create index if not exists mentions_user_published_at_idx
    on public.mentions (user_id, published_at desc);
create index if not exists mentions_user_leader_idx
    on public.mentions (user_id, leader_id);
create index if not exists collection_runs_user_started_at_idx
    on public.collection_runs (user_id, started_at desc);
create unique index if not exists mentions_user_platform_external_id_key
    on public.mentions (user_id, platform, external_id)
    where external_id is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (
        id, email, full_name, phone, organization, role, subscription_plan
    )
    values (
        new.id,
        coalesce(new.email, ''),
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.raw_user_meta_data ->> 'phone', ''),
        coalesce(new.raw_user_meta_data ->> 'organization', ''),
        coalesce(new.raw_user_meta_data ->> 'role', ''),
        case lower(coalesce(new.raw_user_meta_data ->> 'subscription_plan', 'basic'))
            when 'professional' then 'professional'
            when 'enterprise' then 'enterprise'
            else 'basic'
        end
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
    before update on public.profiles
    for each row execute procedure public.set_updated_at();

drop trigger if exists leaders_set_updated_at on public.leaders;
create trigger leaders_set_updated_at
    before update on public.leaders
    for each row execute procedure public.set_updated_at();

-- Populate profiles for accounts created before this migration.
insert into public.profiles (
    id, email, full_name, phone, organization, role, subscription_plan
)
select
    id,
    coalesce(email, ''),
    coalesce(raw_user_meta_data ->> 'full_name', ''),
    coalesce(raw_user_meta_data ->> 'phone', ''),
    coalesce(raw_user_meta_data ->> 'organization', ''),
    coalesce(raw_user_meta_data ->> 'role', ''),
    case lower(coalesce(raw_user_meta_data ->> 'subscription_plan', 'basic'))
        when 'professional' then 'professional'
        when 'enterprise' then 'enterprise'
        else 'basic'
    end
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.leaders enable row level security;
alter table public.mentions enable row level security;
alter table public.collection_runs enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
    for select to authenticated using (id = auth.uid());
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
    for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "leaders_select_own" on public.leaders;
create policy "leaders_select_own" on public.leaders
    for select to authenticated using (user_id = auth.uid());
drop policy if exists "leaders_insert_own" on public.leaders;
create policy "leaders_insert_own" on public.leaders
    for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "leaders_update_own" on public.leaders;
create policy "leaders_update_own" on public.leaders
    for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "leaders_delete_own" on public.leaders;
create policy "leaders_delete_own" on public.leaders
    for delete to authenticated using (user_id = auth.uid());

drop policy if exists "mentions_select_own" on public.mentions;
create policy "mentions_select_own" on public.mentions
    for select to authenticated using (user_id = auth.uid());
drop policy if exists "mentions_insert_own" on public.mentions;
create policy "mentions_insert_own" on public.mentions
    for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "mentions_update_own" on public.mentions;
create policy "mentions_update_own" on public.mentions
    for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "mentions_delete_own" on public.mentions;
create policy "mentions_delete_own" on public.mentions
    for delete to authenticated using (user_id = auth.uid());

drop policy if exists "collection_runs_select_own" on public.collection_runs;
create policy "collection_runs_select_own" on public.collection_runs
    for select to authenticated using (user_id = auth.uid());
